# -*- coding: utf-8 -*-
"""pandas_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WKGwiJBk-jo7zESD4Vnrx7k6wRsTN_zE
"""

import pandas as pd

df=pd.read_csv('/content/job_list.csv')

df

df.shape

df.head(100)

df.columns

df['job_title'].count()

print(df.isnull().sum())

df[['job_title','company_location']]