# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OWZaHC3o9CDKaWacbRsQDcQstQ0MBTDt
"""

#Execute a function named my_function.


def my_function():
  print("Hello from a function")

my_function()